// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/23/2025, 8:49:17 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
import cfg3 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/sergey2/AstroAi_full/front-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sergey2/AstroAi_full/front-nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sergey2/AstroAi_full/front-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sergey2/AstroAi_full/front-nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sergey2/AstroAi_full/front-nuxt/plugins/**/*.{js,ts,mjs}","/home/sergey2/AstroAi_full/front-nuxt/composables/**/*.{js,ts,mjs}","/home/sergey2/AstroAi_full/front-nuxt/utils/**/*.{js,ts,mjs}","/home/sergey2/AstroAi_full/front-nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sergey2/AstroAi_full/front-nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/sergey2/AstroAi_full/front-nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/sergey2/AstroAi_full/front-nuxt/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;